apiVersion: triliovault.trilio.io/v1
kind: Target
metadata:
  name: r1
spec:
  type: NFS
  vendor: Other
  nfsCredentials:
    nfsExport: 1.2.3.4:/mnt1/v2
    nfsOptions: nfsvers=4
  thresholdCapacity: 100gi
