apiVersion: triliovault.trilio.io/v1
kind: TrilioVaultManager
metadata:
  labels:
    triliovault: triliovault
  name: tvm
spec:
  trilioVaultAppVersion: "v2.1.1-alpha"
  helmVersion:
    version: v3
  applicationScope: Cluster
