# etcd.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: etcd-backup-pvc
  namespace: etcd-manual
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: csi-gce-pd
---
apiVersion: v1
kind: Pod
metadata:
  name: etcd-backup-pod
spec:
  volumes:
    - name: etcd-backup
      persistentVolumeClaim:
        claimName: etcd-backup-pvc
  containers:
    - name: inspector
      image: busybox
      command:
        - sleep
        - infinity
      volumeMounts:
        - mountPath: "/backup"
          name: etcd-backup
