apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: minio-1639552971
    meta.helm.sh/release-namespace: minio
  creationTimestamp: "2021-12-15T07:22:56Z"
  generation: 1
  labels:
    app: minio
    app.kubernetes.io/managed-by: Helm
    chart: minio-8.0.10
    heritage: Helm
    release: minio-1639552971
  name: minio-1639552971
  namespace: minio
  resourceVersion: "13189402"
  selfLink: /apis/apps/v1/namespaces/minio/deployments/minio-1639552971
  uid: f670419a-9eab-4cdc-a5ab-30a1447f9867
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: minio
      release: minio-1639552971
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config: 76b8c360e58b06322236b79eb135fca380cb864558dbb1fb9ae781ea00a806ec
        checksum/secrets: 469a7a15c1b592b37f18f0dee5f8f5c049ea95d7cccc10b0a14373d905db6161
      creationTimestamp: null
      labels:
        app: minio
        release: minio-1639552971
      name: minio-1639552971
    spec:
      containers:
      - command:
        - /bin/sh
        - -ce
        - /usr/bin/docker-entrypoint.sh minio -S /etc/minio/certs/ server /export
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: accesskey
              name: minio-1639552971
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: secretkey
              name: minio-1639552971
        image: minio/minio:RELEASE.2021-02-14T04-01-33Z
        imagePullPolicy: IfNotPresent
        name: minio
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
        resources:
          requests:
            memory: 4Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /export
          name: export
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsUser: 1000
      serviceAccount: minio-1639552971
      serviceAccountName: minio-1639552971
      terminationGracePeriodSeconds: 30
      volumes:
      - name: export
        persistentVolumeClaim:
          claimName: minio-1639552971
      - name: minio-user
        secret:
          defaultMode: 420
          secretName: minio-1639552971
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-12-15T07:23:24Z"
    lastUpdateTime: "2021-12-15T07:23:24Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-12-15T07:22:56Z"
    lastUpdateTime: "2021-12-15T07:23:24Z"
    message: ReplicaSet "minio-1639552971-5446bd9767" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
