apiVersion: triliovault.trilio.io/v1
kind: Target
metadata:
  name: minio-test-target2
  namespace: default
spec:
  type: ObjectStore
  vendor: MinIO
  objectStoreCredentials:
    url: "http://minio-1639993582.minio.svc:9000"
    accessKey: "JgwZkbyN1QQkvCoOsGjv"
    secretKey: "Dkjkuua89DC0n9jANa5GYhsGKaGcESZjr9G2HXf2"
    bucketName: "tvk-target123"
    region: "us-east1"
  thresholdCapacity: 100Gi
